export const participants = [
  "Yuval Shoshan",
  "Matan Tessler",
  "Victor Isarov",
  "Ron Ben-Haim",
  "Itai Keren",
  "Noam Baron",
  "Eldad Tzadok",
  "Guy Bercovich",
  "Tal Bar-On",
  "David Sellam",
  "Jonathan Levi",
  "Sapir Rahmani",
  "Shira Attias",
  "Adi Yaacobi",
  "Sahar Nahaisi",
  "Artyom Ivanov",
  "Lior Baraban",
  "Nir Elbaz",
  "Yuval Glizerin",
  "Laure Montuelle",
  "Loren Goldstein",
  "Ran Jarufi",
  "Kim Belassen",
  "Tair Werner",
  "Eli Yarkoni"
];
